# Generated by Django 3.1.6 on 2021-02-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210214_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='File',
        ),
    ]
